/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tele_jni_TestJni */

#ifndef _Included_com_tele_jni_TestJni
#define _Included_com_tele_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tele_jni_TestJni
 * Method:    _get_UID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tele_jni_TestJni__1get_1UID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
